#!/bin/sh
### BEGIN INIT INFO
# Provides:          fanRADIO
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       fanRADIO
### END INIT INFO

start() {
  cd /root/fanRADIO/src/
  /root/fanRADIO/src/radio_init.sh &
}

stop() {
  pkill radio_init.sh
  pkill mplayer
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac