#!/bin/sh
### BEGIN INIT INFO
# Provides:          fanRADIO
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       fanRADIO
### END INIT INFO

start() {
  if [ ! -d "/fanRADIO/" ]; then # init dir if not done yet
	mkdir /fanRADIO/
	cd /fanRADIO/
	git init
	git remote add -t master -f master https://github.com/litzinetz-de/fanRADIO.git
	git checkout master
	git pull
	chmod u+x /fanRADIO/src/*.sh
  else # update from branch
	cd /fanRADIO/
	git pull
  fi
  cd /fanRADIO/src/
  /fanRADIO/src/radio_init.sh &
}

stop() {
  pkill radio_init.sh
  pkill mplayer
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  retart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac